repos:
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
      - id: terraform-fmt
      - id: terraform-validate
      - id: tflint
  # - repo: git@github.com:kabisa/terraform-datadog-pre-commit-hook.git
  - repo: ../terraform-datadog-pre-commit-hook
    #rev: "0.1.4"
    rev: "main"
    hooks:
      - id: terraform-datadog-docs
        exclude: ^README.md$
        args:
        - "."